In [1]:
import pandas as pd
df=pd.read_csv('sales.csv',usecols=['订单号','产品类别','产品名称','销售数量','单价'])
# df['销售金额']=df['销售数量']*df['单价']
# df.to_csv('sales_01.csv',index=False)
# df.head(10)
# df.tail(10)
# df.describe()
# df.info()
# df.shape
# df.columns
# df[['产品名称','单价']]
# df.iloc[0:5:1]
# df[df['销售数量']>=10]
# df[df['产品类别'].isin(['食品','图书'])]
# df[df['单价'].between(100,199,inclusive="left")]
# df[(df['销售数量']>=8) & (df['单价']>100)]
# df[(df['销售数量']>=8) | (df['单价']>100)]

In [26]:
df=pd.read_csv('sales.csv')
df.head(10)
# df.dropna()
# df.fillna('--')
# df.duplicated()
# df.duplicated(subset='订单号')
# df.drop_duplicates(subset='订单号',keep='first')
# df[df['单价']<0]
# df.drop(df[df['单价']<0].index)
# df['订单日期']=df['订单日期'].str.replace('/','-')

          订单号  产品类别  产品名称  销售数量   单价 客户所在城市  支付方式        订单日期
0  6805677496  家居用品    枕头    10  199     合肥   支付宝  2025-06-01
1  5857234132    食品    海苔     5   29     天津    现金  2025-06-01
2  5888085059  电子产品  智能音箱     5  399     福州  微信支付  2025-06-01
3  6823473137    食品    面包     3   29     北京   银行卡  2025-06-02
4  6801664364    食品    薯片     2   19    NaN  微信支付  2025/06/02
5  5897064217    图书    字帖     4   29     广州    现金  2025-06-02
6  6857752388    服装    袜子     7  -29     郑州    现金  2025-06-02
7  6898807429    服装    T恤     6  199     武汉   银行卡  2025-06-02
8  5875402232  电子产品   路由器     9  299     福州   银行卡  2025-06-03
9  5888085066    图书    字典     2   99     青岛  微信支付  2025-06-04

In [33]:
df=pd.read_csv('sales.csv',nrows=10)
df.sort_values('销售数量',ascending=False)
df.sort_values(['单价','销售数量'],ascending=[True,False])

          订单号  产品类别  产品名称  销售数量   单价 客户所在城市  支付方式        订单日期
6  6857752388    服装    袜子     7  -29     郑州    现金  2025-06-02
4  6801664364    食品    薯片     2   19    NaN  微信支付  2025/06/02
1  5857234132    食品    海苔     5   29     天津    现金  2025-06-01
5  5897064217    图书    字帖     4   29     广州    现金  2025-06-02
3  6823473137    食品    面包     3   29     北京   银行卡  2025-06-02
9  5888085066    图书    字典     2   99     青岛  微信支付  2025-06-04
0  6805677496  家居用品    枕头    10  199     合肥   支付宝  2025-06-01
7  6898807429    服装    T恤     6  199     武汉   银行卡  2025-06-02
8  5875402232  电子产品   路由器     9  299     福州   银行卡  2025-06-03
2  5888085059  电子产品  智能音箱     5  399     福州  微信支付  2025-06-01

In [43]:
df=pd.read_csv('sales.csv',nrows=20)
df.groupby('产品类别').count()
df.groupby('产品类别')['销售数量'].sum()
df.groupby('产品类别').agg({'单价':['mean','max','min']})

              单价
            mean  max min
产品类别
图书     51.000000   99  29
家居用品  149.000000  199  49
服装    189.666667  399 -29
电子产品  246.500000  399  89
食品     37.000000   79  19